pipeline {
    agent any

    stages {
        stage('Git Checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Roopak911/Tetris-V1.git']])
            }
        }
        
        stage('Inintialize terraform') {
            steps {
                sh '''
                cd Eks-terraform
                terraform init
                '''
            }
        }
        
         stage('Validate terraform') {
            steps {
                sh 'terraform validate'
            }
        }
        
        stage('Plan terraform') {
            steps {
                sh 'terraform plan'
            }
        }
        
        stage('Apply terraform') {
            steps {
                sh 'terraform ${Action} --auto-approve'
            }
        }
    }
}
